ACC_NAME_LIST = ["X", "Y", "Z"]
PPG_NAME_LIST = ["GPPG", "BPPG", "IPPG", "YPPG"]
ALL_NAME_LIST = [PPG_NAME_LIST, ACC_NAME_LIST]
ALL_NAME_LIST_ONE = ACC_NAME_LIST + PPG_NAME_LIST

DATA_PACKAGE_SIZE = 240
DATASET_COUNT = 10
PPG_COUNT = 4
ACC_COUNT = 3

DATASET_SIZE = 24
PPG_SIZE = 3
ACC_SIZE = 2